case erlang:function_exported(rebar3, main, 1) of
    true -> % rebar3
        CONFIG;
    false -> % rebar 2.x or older
        %% Rebuild deps, possibly including those that have been moved to
        %% profiles
        [{deps, [
            {lager,         ".*",   {git, "https://github.com/chicagoboss-with-deps/lager.git",                {tag, "3.6.7-2"}}},
            {erlando,       ".*",   {git, "https://github.com/chicagoboss-with-deps/erlando.git",               {tag, "rabbitmq_v2_8_8"}}},
            {aleppo,        ".*",   {git, "https://github.com/chicagoboss-with-deps/aleppo.git",                    {tag, "v0.9.4"}}},
            {medici,        ".*",   {git, "https://github.com/chicagoboss-with-deps/medici.git",                    {tag, "1.0.0"}}},

            % Different version of mongodb driver and bson breaking compilation
            % on different Erlang version. So disabling them by default. Uncomment one
            % of options below, if you need mongodb driver
            % for Erlang = 17
            %{bson,          ".*",   {git, "https://github.com/comtihon/bson-erlang",                  {branch, "legacy"}}},
            %{mongodb,       ".*",   {git, "https://github.com/comtihon/mongodb-erlang",               {tag, "v0.7.9"}}},
            % for Erlang >= 18
            %{mongodb,       ".*",   {git, "https://github.com/comtihon/mongodb-erlang",               {tag, "v0.7.9"}}},
            {mongodb,        ".*",   {git, "https://github.com/chicagoboss-with-deps/mongodb-erlang.git",            {tag, "0.9.0-3"}}},

            % riak_pb not compatible with Erlang 18, so commented for now
            % uncomment line below if you need Riak support and have Erlang < 18
            %{riakc,         ".*",   {git, "https://github.com/ErlyORM/riak-erlang-client.git",        {tag, "1.3.0-boss"}}},

            {ddb,           ".*",   {git, "https://github.com/chicagoboss-with-deps/ddb.git",                       {tag, "v0.1.8"}}},
            {epgsql,        ".*",   {git, "https://github.com/chicagoboss-with-deps/epgsql.git",                     {tag, "4.2.0-2"}}},
            {erlmc,         ".*",   {git, "https://github.com/chicagoboss-with-deps/erlmc.git",                   {tag, "0.4.1"}}},
            {mysql,         ".*",   {git, "https://github.com/chicagoboss-with-deps/erlang-mysql-driver.git",       {tag, "v0.0.4"}}},
            {poolboy,       ".*",   {git, "https://github.com/chicagoboss-with-deps/poolboy.git",                   {tag, "1.5.3"}}},
            {uuid,          ".*",   {git, "https://github.com/chicagoboss-with-deps/erlang-uuid.git",              {tag, "v0.5.2"}}},
            {redo,          ".*",   {git, "https://github.com/chicagoboss-with-deps/redo.git",                       {tag, "cd75a11"}}},
                                                                                                    % boss_branch for ets_cache
            {ets_cache,     ".*",   {git, "https://github.com/chicagoboss-with-deps/ets_cache.git",                 {tag, "c7a17204cd"}}},
            {proper,        ".*",   {git, "https://github.com/chicagoboss-with-deps/proper.git",                  {tag, "v1.3"}}},
            {dh_date,       ".*",   {git, "https://github.com/chicagoboss-with-deps/dh_date.git",                {tag, "23e5a61"}}},
            {tiny_pq,       ".*",   {git, "https://github.com/chicagoboss-with-deps/tiny_pq.git",               {tag, "v0.9.0"}}},
            {boss_test,     ".*",   {git, "https://github.com/chicagoboss-with-deps/boss_test.git",             {tag, "0.0.1"}}}
        ]}
        ,{plugins, [rebar_ct]}
        ,{erl_opts, [
            debug_info,
            {parse_transform, lager_transform},
            {parse_transform, cut},
            {parse_transform, do},
            {parse_transform, import_as}
        ]} | [Config || {Key, _Value}=Config <- CONFIG, Key =/= deps andalso Key =/= plugins andalso Key =/= erl_opts]]
end.
